### ISSUE TITLE
Add a command line option to strip verse numbers

### ISSUE THREAD

**Issue by esturcke** [covode/bible-fetch#5]
We should be able to optionally strip out verse numbers form the output. Perhaps something like:

```
./bible --no-verse psalm 23
```

[Argparse](https://docs.python.org/3/library/argparse.html) looks promising.

**Comment by bentsai** [comment]
I'm trying to figure out how to use argparse to continue parsing the reference in the command line such that everything except the last argument is parsed as a reference.
